[workspace]
members = [
  "zomes/social_context"
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hdk3 = { git = "https://github.com/holochain/holochain.git", rev = "fd8049a" }
holo_hash = { git = "https://github.com/holochain/holochain.git", rev = "fd8049a" }