name: CI

on:
  push:
    tags:
    - '*'

jobs:
  release:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Fetch source code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Use Nix
      uses: cachix/install-nix-action@v12
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Configure Nix substituters
      run: |
        set -xe
        mkdir -p ~/.config/nix/
        cp ./.github/nix.conf ~/.config/nix/
    - uses: cachix/cachix-action@v10
      with:
        name: perspect3vism
        # authToken: '${{ secrets.CACHIX_HOLOCHAIN_CI }}'
    - name: Prepare Nix environment
      run: nix-shell --command "echo Completed"
    - name: Release languages
      run: ./release.sh
    - name: Upload released files
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release/full_features/bundle.js, release/full_features/social-context.dna, release/full_features.zip, release/basic.zip, release/signals.zip, release/time_index.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true  
